name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'  # Set to Java 17 or your desired version

      - name: Generate Changelog
        id: generate_changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0
        continue-on-error: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes and documentation here.
            $(cat CHANGELOG.md)

      - name: Upload Artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: build/libs  # Update this path to your build artifacts location

      - name: Update Release with Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.upload_artifacts.outputs.artifact_path }}
          asset_name: release-artifacts.zip  # Update with your artifact file name
          asset_content_type: application/zip
